require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "node_modules/**/*"
    - ".git/**/*"

# Layout cops
Layout/LineLength:
  Max: 1000

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Style cops
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: false

# For algorithm problems, we often use single letter variables
Naming/MethodParameterName:
  Enabled: false

Naming/VariableName:
  Enabled: false

# Allow TODO comments in algorithm files
Style/CommentAnnotation:
  Enabled: false

# Disable all metrics for algorithm files
Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
